from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(Discipline)
admin.site.register(Profile)
admin.site.register(DisciplineForEvent)
admin.site.register(Sport)
admin.site.register(TypeSport)
admin.site.register(TypeDiscipline)
admin.site.register(TypeEvent)
admin.site.register(Event)
admin.site.register(Organizer)
admin.site.register(OrganizerForEvent)
admin.site.register(Participant)
admin.site.register(ParticipantForEvent)
admin.site.register(Worker)
admin.site.register(WorkerForEvent)
admin.site.register(Judge)
admin.site.register(JudgeForEvent)
admin.site.register(Viewer)
admin.site.register(ViewerForEvent)
admin.site.register(Application)
admin.site.register(Files)
admin.site.register(FilesForEvent)
admin.site.register(Invite)
admin.site.register(City)