# Generated by Django 4.1.2 on 2023-05-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizationapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.profile')),
            ],
            options={
                'db_table': 'Judge',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.profile')),
            ],
            options={
                'db_table': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.profile')),
            ],
            options={
                'db_table': 'Worker',
            },
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='sex',
        ),
        migrations.AddField(
            model_name='organizer',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizationapp.profile'),
        ),
        migrations.CreateModel(
            name='WorkerForEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.event')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.worker')),
            ],
            options={
                'db_table': 'WorkerForEvent',
            },
        ),
        migrations.CreateModel(
            name='ParticipantForEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.participant')),
            ],
            options={
                'db_table': 'ParticipantForEvent',
            },
        ),
        migrations.CreateModel(
            name='JudgeForEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.event')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.judge')),
            ],
            options={
                'db_table': 'JudgeForEvent',
            },
        ),
    ]
