# Generated by Django 4.1.2 on 2023-05-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizationapp', '0004_sponsor_event_if_active_sponsorforevent_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='if_active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='results',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
