# Generated by Django 4.1.2 on 2023-05-12 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizationapp', '0008_alter_judgeforevent_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.profile')),
            ],
            options={
                'db_table': 'Viewer',
            },
        ),
        migrations.CreateModel(
            name='ViewerForEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.event')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.viewer')),
            ],
            options={
                'db_table': 'ViewerForEvent',
                'unique_together': {('event', 'viewer')},
            },
        ),
    ]
