# Generated by Django 4.1.2 on 2023-05-12 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizationapp', '0009_viewer_viewerforevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
            options={
                'db_table': 'Files',
            },
        ),
        migrations.CreateModel(
            name='FilesForEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.event')),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizationapp.files')),
            ],
            options={
                'db_table': 'FilesForEvent',
            },
        ),
    ]
