# Generated by Django 4.1.2 on 2023-05-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationapp', '0013_city_event_sport_event_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
    ]
