# Generated by Django 4.1.2 on 2023-05-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizationapp', '0014_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('profile', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('profile', 'event')},
        ),
    ]
